version: '3.8'

services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: books_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books_app
      MYSQL_USER: books
      MYSQL_PASSWORD: books
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - books_network

  # PHP/Symfony Application
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: books_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - books_network
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://books:books@database:3306/books_app

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: books_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - books_network
    depends_on:
      - php

  # Node.js for Vue 3 development
  node:
    image: node:18-alpine
    container_name: books_node
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "3000:3000"
      - "5173:5173"
    networks:
      - books_network
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:

networks:
  books_network:
    driver: bridge
